server:
  port: 8787

spring:
  application:
    name: "qafordevs"
  datasource:
    url: jdbc:postgresql://localhost:5432/habrdb
    username: habrpguser
    password: pgpwd4habr
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
